### PR TITLE
Switch to BroadcastChan

### PR DESCRIPTION
**Pull request by amurrayc**
This should fix zero reader leaks, notably in the Network and Battery
widgets.

Does not use the extra error reporting granted by write/readBChan.

Resolves: #352

### CODE REVIEW

**Comment by amurrayc** [comment]
`writeBChan` returns `m Bool` and `readBChan` returns `m (Maybe a)` instead of `IO ()` and `IO a` respectively to indicate potential failure modes.  I'm ignoring them at the moment.

Also `Chan` remains in `SafeX11.hs`.

The github fork of broadcast-chan in `stack-8.6.yaml` is required for ghc 8.6 support.

**Comment by IvanMalison** [comment]
> The github fork of broadcast-chan in `stack-8.6.yaml` is required for ghc 8.6 support.

Oh damn, thats a blocker. Is there going to be a release soon?

**Comment by amurrayc** [comment]
There's a pull request but it loses <ghc8.0 support.

I'm having a look to see if there is another way to do it.

**Comment by IvanMalison** [comment]
@amurrayc I'm fine with dropping < 8.0 support actually.

**Comment by amurrayc** [comment]
@IvanMalison Yes.  I guess it's about whether the author of broadcast-chan is willing to do so.

It seems to be all about the MonadFail refactor.  I'm looking to see if there is a way to make the changes in a less disruptive way.

**Comment by amurrayc** [comment]
Hopefully merijn/broadcast-chan#8 will get merged soon. See https://github.com/merijn/broadcast-chan/pull/8#issuecomment-476526805.

As soon as there is a release I'll amend this PR.

**Comment by merijn** [comment]
> `writeBChan` returns `m Bool` and `readBChan` returns `m (Maybe a)` instead of `IO ()` and `IO a` respectively to indicate potential failure modes. I'm ignoring them at the moment.

Note that that the `BroadcastChan.Throw` is identical to `BroadcastChan`, but with `readBChan` and `writeBChan` replaced with exception throwing versions :)

I'm fixing the Travis tests and GHC-8.6 build now, I will upload a new release to Hackage sometime this weekend/early next week.

**Comment by IvanMalison** [comment]
@merijn Great. Feel free to post here when that happens!

**Comment by merijn** [comment]
And done: [broadcast-chan-0.2.0.2](https://hackage.haskell.org/package/broadcast-chan-0.2.0.2)

**Pull request merged**
