### PR TITLE
Write ChangeLog for v4.0.3

### PR DESCRIPTION
**Pull request by rvl**
- Adds changelog entries
- Add a deprecated alias of a function that I renamed.
- Tweak the cabal file to make it more suitable for upload.

### CODE REVIEW

**Comment by colonelpanic8** [comment]
@rvl are you still doing stuff you want to get in before 4.0.3?

**Comment by rvl** [comment]
Just merging #593 and #595, then that should be enough, thanks @colonelpanic8.

**Comment by colonelpanic8** [comment]
@rvl what is your package handle. I'll just add you there so you can do it yourself when you think it's ready.

**Comment by rvl** [comment]
OK, thanks @colonelpanic8, my Hackage username is `rvl`.

**Comment by colonelpanic8** [comment]
looks good?: https://hackage.haskell.org/package/taffybar/maintainers/

**Comment by rvl** [comment]
Yep :+1: thanks @colonelpanic8. I will try uploading a package candidate.

**Comment by rvl** [comment]
@colonelpanic8, here is the package candidate upload:
https://hackage.haskell.org/package/taffybar-4.0.3/candidate

**Comment by colonelpanic8** [comment]
Oh one thing to know is that documentation needs to be uploaded manually, because the package servers can't build it because they don't have the non haskeel dependencies. Do you know how to do that? Should I show you how?

**Comment by rvl** [comment]
Aha, I was wondering about that. I have uploaded the docs to the candidate package now.

**Pull request merged**
