### PR TITLE
Allow batteryIcon styling (issue #382)

### PR DESCRIPTION
**Pull request by amurrayc**
This allows the battery icon to take its colour from `taffybar.css`. By
default it uses the `color` attribute from the top `.taffy-window` class
but can be overridden in the `.auto-size-image` class.

Related to #382

### CODE REVIEW

**Comment by IvanMalison** [comment]
@amurrayc Very cool. Nice work!

**Comment by IvanMalison** [comment]
Not sure I would say this fixes #382 since this still seems to use static images.

**Comment by amurrayc** [comment]
Agreed. However, that issue started as a bugreport (can't get battery icon to be white) and then expanded into a feature request (dynamically drawn battery widget).

This fixes the bug but does nothing for the feature request. :)

**Comment by IvanMalison** [comment]
> Agreed. However, that issue started as a bugreport (can't get battery icon to be white) and then expanded into a feature request (dynamically drawn battery widget).

Ahh didnt realize that

**Pull request merged**
