### PR TITLE
add CSS class to `Layout`

### PR DESCRIPTION
**Pull request by dlahoti**
Gives the label in `Layout` the class `layout-label` so that it can be styled with CSS.

### CODE REVIEW

**Comment by IvanMalison** [comment]
Was about to merge, but noticed the build failed. I think it might be a really weird flake, but can't be sure. any ideas?

**Comment by IvanMalison** [comment]
Wait, nvm, looks like the error is here:

https://travis-ci.org/taffybar/taffybar/builds/495689768#L1203

Seems like you need a text value rather than a string value.

How are you building this locally? You might be using a different version of gdk or gtk bindings?

**Comment by dlahoti** [comment]
Looks like I forgot to add `OverloadedStrings` – my local version has some other changes, so I had just manually copied over the relevant ones here.

**Comment by IvanMalison** [comment]
@dlahoti What changes? Are they not worth merging?

**Comment by dlahoti** [comment]
I have the local version in my `.config/taffybar/lib/` folder, so it has various name changes to avoid conflicting with the existing version.

**Pull request merged**
