### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by rvl**
Covering issues #535 #332 #308

### CODE REVIEW

**Comment by colonelpanic8** [comment]
@rvl do you want me to add you to the taffybar org so you can help out with maintenence?

Honestly I don't have the time to look through all the PRs you are making as thoroughly as I would like and it might be easier for me to just let you merge stuff on your own as long as you can be responsible about doing so.

**Comment by rvl** [comment]
Yes please @colonelpanic8 - I'm keen to help out with maintenance.

**Comment by colonelpanic8** [comment]
@rvl i sent you an invite, but it doesn't look like you accepted yet

**Comment by rvl** [comment]
Received, thanks :+1:.

**Review by colonelpanic8 — APPROVED** [review]

**Pull request merged**
