### PR TITLE
Build with ghc-8.2.2 using Nix

### PR DESCRIPTION
**Pull request by PierreR**
This is not ready to be merged.

I would like to discuss this PR to get feedback and help.

This PR allows me to install `Taffybar` compiled with ghc-8.2.2. This is necessary because of https://github.com/taffybar/taffybar/issues/358.

You can try it out in nixos (and I guess also with nix and other linux distro) by using this command:
```
nix-env -i -f https://github.com/pierrer/taffybar/tarball/20584dafc952fbe5ee36136e0492500749ea7faa
```

It is going to take quite a while because a lot of the dependencies are not in the nixos default binary cache.

One issue remains. It works on the stable nixos channel (18.03) but it won't work so well when I use the unstable channel (18.09). In `18.09` it completes the building process without problem but Taffybar will fail to recompile the user configuration. It complains that it can't find the imported taffybar modules.

As a bonus, I would also like to speed up the build/compilation process (by disabling profiling globally, using `justStaticExecutables´, ...). Any idea or suggestion welcomed.

When I am happy about the workflow I will probably push it to [cachix](https://cachix.org/)

Thanks for your help and feedback.

### CODE REVIEW

**Comment by IvanMalison** [comment]
Thanks for submitting, this should be helpful to a lot of people. I'll try it out on my machine in the near future.

**Comment by IvanMalison** [comment]
@PierreR I'm confused. Why does this need to exist at all. Seems like we should just use the existing nixpkgs derivations for taffybar.

**Comment by PierreR** [comment]
Yep it can be removed now that everything is working correctly in nixpkgs

**Comment by PierreR** [comment]
I can do a PR to clean this up.

**Pull request merged**
