### PR TITLE
GitHub actions: test more GHC versions and nixos stable

### PR DESCRIPTION
**Pull request by rvl**
This expands the CI matrix.

### CODE REVIEW

**Review by colonelpanic8 — APPROVED** [review]

**Comment by rvl** [comment]
I would like to merge this @colonelpanic8.
I am a member of the [taffybar org](https://github.com/orgs/taffybar/people), but I don't think membership alone grants write access to the taffybar repo. Probably some role/permission needs to be assigned ([github doc](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization)). Thanks.

**Comment by colonelpanic8** [comment]
K I'll look in to it

**Comment by colonelpanic8** [comment]
@rvl I think you should be good to go now

**Comment by colonelpanic8** [comment]
should we do a release soon?

I can add you on hackage if you want.

**Comment by rvl** [comment]
Thanks, looks like I can merge now.
A release sounds good.
But first I would like to make a PR with some haddock edits, and add a couple deprecation warnings.

**Pull request merged**
